# .github/workflows/cd.yml
name: CD - Deploy Trained Model to SageMaker

on:
  workflow_run:
    workflows: ["CI - Train and Upload Model"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform/cd
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform/cd
        run: terraform apply -auto-approve -var="s3_bucket=my-ml-models-iris" -var="sagemaker_role_arn=${{ secrets.SAGEMAKER_ROLE_ARN }}"

      - name: Install dependencies
        run: pip install boto3

      - name: Run Prediction
        run: python predict.py iris-endpoint

      - name: Destroy endpoint
        if: always()
        working-directory: terraform/cd
        run: terraform destroy -auto-approve -var="s3_bucket=my-ml-models-iris" -var="sagemaker_role_arn=${{ secrets.SAGEMAKER_ROLE_ARN }}"